apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-vh2r
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0040-tenant/tkrw-pr712-0075-0040-app/devfile-sample-vh2r@sha256:8e2f7a104beba72050845519ddc741f0f83c2113760480578f4a53d2d4eeef1d
        name: my-nodejs
        resources: {}
status: {}
